# Generated by Django 5.2.8 on 2026-01-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_award_nomination_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['name'], 'verbose_name': 'Премия', 'verbose_name_plural': 'Премии'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'ordering': ['name'], 'verbose_name': 'Номинация', 'verbose_name_plural': 'Номинации'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
    ]
